Employee.create(name: "Ulises Pacheco", email: "upacheco@pernix-solutions.com")
Employee.create(name: "Abraham Sibaja", email: "asibaja@pernix-solutions.com")
Employee.create(name: "Jose Alvarez", email: "jalvarez@pernix-solutions.com")
Employee.create(name: "Pablo Bonilla", email: "pbonilla@pernix-solutions.com")
Employee.create(name: "Brayan Zuñiga", email: "brayan@pernix-solutions.com")
Employee.create(name: "Jose Chacon", email: "jchacon@pernix-solutions.com")
Employee.create(name: "Jonathan Avalos", email: "javalos@pernix-solutions.com")
Employee.create(name: "Danilo Sanchez", email: "dsanchez@pernix-solutions.com")
Employee.create(name: "Gabriel Madriz", email: "gmadriz@pernix-solutions.com")
Employee.create(name: "Cesar Navarro", email: "cnavarro@pernix-solutions.com")
Employee.create(name: "Esteban Hernandez", email: "ehernandez@pernix-solutions.com")
Employee.create(name: "Satcha Villafuerte", email: "svillafuerte@pernix-solutions.com")
Employee.create(name: "Fernanda Coto", email: "fcoto@pernix-solutions.com")
Employee.create(name: "Carlos Sirias", email: "csirias@pernix-solutions.com")
Employee.create(name: "Arnaldo Porras", email: "aporras@pernix-solutions.com")
Employee.create(name: "Erick Castillo", email: "ecastillo@pernix-solutions.com")

Badge.create(title: "Patrones (Software Patterns)", points: 2, description: "Identifica y aplica patrones. Manifiesta los costos / beneficios del patrón. Se expone al grupo")
Badge.create(title: "TDD", points: 8, description: "Realiza pruebas unitarias y de aceptación de manera inmaculada. Las pruebas automatizadas siempre funcionan en master. Se expone al grupo")
Badge.create(title: "Refactoring", points: 8, description: "Tomó un proyecto existente y aplicó refactoring significativo para implementar nuevas funcionalidades. Se expone al grupo")
Badge.create(title: "Principios de diseño", points: 8, description: "Aplica principios de diseño SOLID. Se expone al grupo")
Badge.create(title: "Políglota", points: 8, description: "Aprendió un nuevo lenguaje e hizo el gato de los aprendices con los patrones.")
Badge.create(title: "Enseña (Teach)", points: 5, description: "Crea presentaciones. Enseña nuevos métodos, patrones, tecnologías a sus compañeros. Realiza resúmenes de aspectos que le interesa y los comparte con sus compañeros. Completa cursos del área de recursos.")
Badge.create(title: "Involucramiento en la comunidad (Community)", points: 5, description: "Escribe regularmente en el blog. Organiza / contribuye con grupos de usuarios o eventos")
Badge.create(title: "Compañerismo (Teammates)", points: 2, description: "Dedicó medio día de su trabajo para ayudar a un compañero a resolver un problema, sin descuidar sus obligaciones actuales.")
Badge.create(title: "Pair Programming", points: 2, description: "Es efectivo al realizar una programación en parejas, hace el intercambio del teclado (ping/pong) con frecuencia.")
Badge.create(title: "Agilidad (Being Agile)", points: 2, description: "Trabaja en iteraciones, guía demos, completa “features”, guía standups y retrospectivas.")
Badge.create(title: "Colaboración con el cliente (Customer Collaboration)", points: 2, description: "Crea “features” / criterios de aceptación con base en discusiones con el cliente.")
Badge.create(title: "GIT Master", points: 1, description: "Aportó sus conocimientos avanzados para ayudar a otros compañeros.")

Status.create(status: "Accept")
Status.create(status: "Deny")
Status.create(status: "N/A")
